#======================================================================#
#== ṔASO 2: Hacemos la conexión entre el proyecto y la base de datos ==#
#======================================================================#

# spring.application.name=todo-api
# Temporal to be able to run correctly
# spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

# Configuración de la conexión (Con las variables de entorno)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/todo_db}
spring.datasource.username=${DB_USER:todo_user}
spring.datasource.password=${DB_PASSWORD:todo_password}

# Configuración de JPA / Hibernate: Orientado a la base de datos (esta dirije)
# Lo que significa que la base de datos se crea antes, luego se agregan datos con JPA (ORM)
spring.jpa.hibernate.ddl-auto=validate

# Mostrar el SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true